# Generated by Django 3.1.4 on 2020-12-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sexa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('review', models.TextField()),
                ('review2', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
